services:
  mongodb:
    image: mongo:latest
    container_name: mongo-library
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: notification
      MONGO_INITDB_AUTH_SOURCE: admin
    command: --auth
